image: gitpod/workspace-python-3.13

vscode:
  extensions:
    - almenon.arepl
    - ms-python.python
    - littlefoxteam.vscode-python-test-adapter
    - ms-azuretools.vscode-docker
    - laike9m.cyberbrain